In [18]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [28]:
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

In [30]:
#텐서를 위한 플레이스홀더를 항상 피드할 것임
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [31]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 +b 

In [32]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# 데이터 셋에 대해 매우 작은 learning_rate를 설정하여 미니마이즈 
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [33]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
 for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                      feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        if step % 10 == 0:
            print(step, "Cost : ", cost_val, "\nPrediction :\n" , hy_val)

0 Cost :  48553.4 
Prediction :
 [-37.64294052 -54.33673477 -48.37343979 -57.58651352 -39.82432175]
10 Cost :  14.8069 
Prediction :
 [ 157.23838806  179.92158508  182.43196106  193.75712585  138.86019897]
20 Cost :  14.2991 
Prediction :
 [ 157.81454468  180.63955688  183.12606812  194.51530457  139.41223145]
30 Cost :  14.2361 
Prediction :
 [ 157.80282593  180.65087891  183.12393188  194.51531982  139.42523193]
40 Cost :  14.1734 
Prediction :
 [ 157.78938293  180.66004944  183.11973572  194.51304626  139.43659973]
50 Cost :  14.1111 
Prediction :
 [ 157.77597046  180.66915894  183.11549377  194.51078796  139.44790649]
60 Cost :  14.049 
Prediction :
 [ 157.76257324  180.67828369  183.11129761  194.50852966  139.459198  ]
70 Cost :  13.9873 
Prediction :
 [ 157.74920654  180.68733215  183.1071167   194.50627136  139.47044373]
80 Cost :  13.926 
Prediction :
 [ 157.73588562  180.6963501   183.10292053  194.50401306  139.48164368]
90 Cost :  13.8649 
Prediction :
 [ 157.72261047  180.

800 Cost :  10.263 
Prediction :
 [ 156.86383057  181.28860474  182.82855225  194.36109924  140.21203613]
810 Cost :  10.2213 
Prediction :
 [ 156.85284424  181.29605103  182.82507324  194.35932922  140.22119141]
820 Cost :  10.1797 
Prediction :
 [ 156.84190369  181.30351257  182.82159424  194.35762024  140.2303009 ]
830 Cost :  10.1385 
Prediction :
 [ 156.83094788  181.31088257  182.81813049  194.35586548  140.23936462]
840 Cost :  10.0975 
Prediction :
 [ 156.82006836  181.31828308  182.81472778  194.35412598  140.2484436 ]
850 Cost :  10.0567 
Prediction :
 [ 156.80918884  181.32566833  182.81132507  194.35243225  140.25747681]
860 Cost :  10.016 
Prediction :
 [ 156.79833984  181.33305359  182.80789185  194.35072327  140.26646423]
870 Cost :  9.97564 
Prediction :
 [ 156.78753662  181.34036255  182.80445862  194.34899902  140.27548218]
880 Cost :  9.93541 
Prediction :
 [ 156.7767334   181.34768677  182.80105591  194.34732056  140.28442383]
890 Cost :  9.89552 
Prediction :
 [ 15

1590 Cost :  7.55982 
Prediction :
 [ 156.07910156  181.82055664  182.58033752  194.24142456  140.8596344 ]
1600 Cost :  7.53228 
Prediction :
 [ 156.07017517  181.82659912  182.57749939  194.24009705  140.86694336]
1610 Cost :  7.50486 
Prediction :
 [ 156.06124878  181.83259583  182.57466125  194.23880005  140.87420654]
1620 Cost :  7.47756 
Prediction :
 [ 156.05236816  181.83863831  182.57185364  194.23751831  140.88146973]
1630 Cost :  7.4505 
Prediction :
 [ 156.04351807  181.84460449  182.56906128  194.23623657  140.88870239]
1640 Cost :  7.42347 
Prediction :
 [ 156.03465271  181.85058594  182.56625366  194.23493958  140.89590454]
1650 Cost :  7.39665 
Prediction :
 [ 156.02586365  181.85653687  182.5634613   194.23368835  140.90312195]
1660 Cost :  7.3699 
Prediction :
 [ 156.01707458  181.86250305  182.56063843  194.23240662  140.91029358]
1670 Cost :  7.34329 
Prediction :
 [ 156.00830078  181.86846924  182.55789185  194.23117065  140.91744995]
1680 Cost :  7.31683 
Predicti